#spring:
#  profiles:
#    active:
#      - dev
#---
#server:
#  port: 8080
#
#spring:
#  profiles: dev
#
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://101.101.209.179:3306/dev_db
#    username: root
#    password: #!@bside1303
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#---
#server:
#  port: 8081
#
#spring:
#  profiles: prd
#
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://101.101.209.179:3306/db
#    username: root
#    password: #!@bside1303
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl