server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://101.101.209.179:3306/db
    username: root
    password: "#!@bside1303"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: BSIDE_ROLEBIT_AUTHENTICATE_ENCRYPT_KEY
    tokenExpiry: 1800000 # milliseconds, 30min
    refreshTokenExpiry: 1209600000 # milliseconds, 14days
file-path:
  routineFile: /svc/routine
  routineImage: /svc/routine/image
  profileImage: /svc/profile_image
fcm:
  certification: RolebitNotificationKey.json